DATABASE_URI:
DATABASE_MODEL_PATH: db.models
DATABASE_TIMEZONE: UTC
DATABASE_USE_TZ: True

USE_DOCKER:

TORTOISE_APP_NAME: YourBot

BOT_NAME: YourBot
DISCORD_ID:
DISCORD_TOKEN:

BOT_OWNERS: []
SERVER_BLACKLIST_CHANNEL_ID:
MAINTENANCE_MODE: False

RUN_LAUNCHER_WITH_EXTRA_SYS_INFO: True

DEFAULT_REDIS_PATH: C:/Redis
REDIS_URI: redis://localhost:6379


OSU_API_V1_KEY:
OSU_API_V2_CLIENT_ID:
OSU_API_V2_CLIENT_SECRET:
OSU_API_V2_CLIENT_CALLBACK_URL: http://localhost:727 #  ඞ

BITLY_API_TOKEN:

DEFAULT_PREFIX: "-"
BOT_VERSION: "1.0.0"
BOT_LOGS_CHANNEL_ID:

RPC_ENABLED:
RPC_LARGE_IMAGE:
RPC_LARGE_TEXT:
RPC_SMALL_IMAGE:
RPC_SMALL_TEXT:

PRAW_ID:
PRAW_SECRET:

YOUTUBE_API_KEY:

SPOTIFY_CLIENT_ID:
SPOTIFY_CLIENT_SECRET:

TWITCH_API_ID:
TWITCH_API_SECRET:

X_RAPID_API_KEY:
X_RAPID_API_HOST: mashape-community-urban-dictionary.p.rapidapi.com

SOME_RANDOM_API_KEY:

STATCORD_API_KEY:

DAGPI_API_KEY:

KAWAII_RED_API_TOKEN:

GENIUS_API_TOKEN:

API_FLASH_TOKEN:

AZREAL_API_TOKEN:

RANDOM_STUFF_API_KEY:
